"""add_password_and_role_to_employee

Revision ID: 42fb1458f926
Revises: 0956cc1230e4
Create Date: 2026-06-01 14:12:58.397344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")

# revision identifiers, used by Alembic.
revision: str = "42fb1458f926"
down_revision: Union[str, Sequence[str], None] = "0956cc1230e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("role", _ROLE_ENUM, server_default="Developer")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
