"""Status Enum

Revision ID: 7f262a3d2052
Revises: c4110bf405eb
Create Date: 2026-06-10 16:18:57.111633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_STATUS_ENUM = sa.Enum("Probation", "Active", "Inactive", name="employeestatus")

# revision identifiers, used by Alembic.
revision: str = "7f262a3d2052"
down_revision: Union[str, Sequence[str], None] = "c4110bf405eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("status", _STATUS_ENUM, server_default="Probation")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "status")
    # ### end Alembic commands ###
