"""init

Revision ID: 85c22b59f90d
Revises: eadd3636f4ea
Create Date: 2026-05-28 17:28:37.056970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85c22b59f90d"
down_revision: Union[str, Sequence[str], None] = "eadd3636f4ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Address", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_Address_employee_id"), "Address", ["employee_id"], unique=False
    )
    op.create_foreign_key(
        None, "Address", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Address", type_="foreignkey")
    op.drop_index(op.f("ix_Address_employee_id"), table_name="Address")
    op.drop_column("Address", "employee_id")
    # ### end Alembic commands ###
