"""Unique Constraint

Revision ID: c4110bf405eb
Revises: 42fb1458f926
Create Date: 2026-06-02 13:09:43.889091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4110bf405eb"
down_revision: Union[str, Sequence[str], None] = "42fb1458f926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "employee_department", ["emp_id", "dept_id"])
    op.drop_constraint(
        op.f("employee_department_dept_id_fkey"),
        "employee_department",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("employee_department_emp_id_fkey"),
        "employee_department",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "employee_department",
        "departments",
        ["dept_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "employee_department", "employees", ["emp_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "employees",
        "role",
        existing_type=postgresql.ENUM(
            "UI", "UX", "Developer", "HR", name="employeerole"
        ),
        nullable=False,
        existing_server_default=sa.text("'Developer'::employeerole"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "role",
        existing_type=postgresql.ENUM(
            "UI", "UX", "Developer", "HR", name="employeerole"
        ),
        nullable=True,
        existing_server_default=sa.text("'Developer'::employeerole"),
    )
    op.drop_constraint(None, "employee_department", type_="foreignkey")
    op.drop_constraint(None, "employee_department", type_="foreignkey")
    op.create_foreign_key(
        op.f("employee_department_emp_id_fkey"),
        "employee_department",
        "employees",
        ["emp_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("employee_department_dept_id_fkey"),
        "employee_department",
        "departments",
        ["dept_id"],
        ["id"],
    )
    op.drop_constraint(None, "employee_department", type_="unique")
    # ### end Alembic commands ###
